const products = [
  {
    id: 1,
    image: "products/p1.jpg",
    title: "perfume",
    price: "3200",
    d_price: "7000",
    quantity: 1,
  },
  {
    id: 2,
    image: "products/p2.jpg",
    title: "men shirt",
    price: "1200",
    d_price: "2000",
    quantity: 1,
  },
  {
    id: 3,
    image: "products/p3.jpg",
    title: "men hoodie",
    price: "3200",
    d_price: "4000",
    quantity: 1,
  },
  {
    id: 4,
    image: "products/p4.jpg",
    title: "men sweater",
    price: "6200",
    d_price: "8200",
    quantity: 1,
  },
  {
    id: 5,
    image: "products/p5.jpg",
    title: "men t-shirt",
    price: "4000",
    quantity: 1,
    d_price: "9000",
  },
  {
    id: 6,
    image: "products/p6.jpg",
    title: "men jshirt",
    quantity: 1,
    price: "1200",
    d_price: "92000",
  },
  {
    id: 7,
    image: "products/p7.jpg",
    quantity: 1,
    title: "men shirt",
    price: "6200",
    d_price: "2000",
  },
  {
    id: 8,
    image: "products/p8.jpg",
    title: "men shirt",
    price: "2200",
    d_price: "2000",
  },
  {
    id: 9,
    image: "products/p9.jpg",
    title: "men shirt",
    price: "7800",
    d_price: "2000",
  },
  {
    id: 10,
    image: "products/p10.jpg",
    title: "men shirt",
    quantity: 1,
    price: "190",
    d_price: "2000",
  },
  {
    id: 11,
    image: "products/p11.jpg",
    quantity: 1,
    title: "CACTUS 10ML",
    price: "120",
    d_price: "2000",
  },
  {
    id: 12,
    image: "products/p12.jpg",
    title: "CACTUS 10ML",
    quantity: 1,
    price: "130",
    d_price: "2000",
  },
];

export default products;
