const wproducts = [
  {
    id: 1,
    image: "products/w4.jpg",
    title: "Women Hoodie",
    price: "2200",
    quantity: 1,
    d_price: "4000",
  },
  {
    id: 2,
    image: "products/w5.jpg",
    title: "Girl Sweater",
    quantity: 1,
    price: "3000",
    d_price: "4000",
  },
  {
    id: 3,
    image: "products/w6.jpg",
    title: "Hoodie",
    quantity: 1,
    price: "3500",
    d_price: "6000",
  },
  {
    id: 4,
    image: "products/w7.jpg",
    title: "Girl hoodie",
    price: "5000",
    quantity: 1,
    d_price: "7000",
  },
  {
    id: 5,
    image: "products/w2.jpg",
    title: "hoodie",
    price: "1200",
    quantity: 1,
    d_price: "3500",
  },
  {
    id: 6,
    image: "products/w4.jpg",
    title: "Women Pants",
    quantity: 1,
    price: "2990",
    d_price: "4000",
  },
  {
    id: 7,
    image: "products/w1.jpg",
    title: "Women Trouser",
    price: "8200",
    quantity: 1,
    d_price: "2000",
  },
  {
    id: 8,
    image: "products/w2.jpg",
    title: "girl trouser",
    quantity: 1,
    price: "1500",
    d_price: "2000",
  },
  {
    id: 9,
    image: "products/w3.jpg",
    title: "girl trouser",
    quantity: 1,
    price: "1800",
    d_price: "2000",
  },
  {
    id: 10,
    image: "products/w1.jpg",
    title: "girl hoodie",
    price: "1200",
    quantity: 1,
    d_price: "2000",
  },
  {
    id: 11,
    image: "products/w2.jpg",
    title: "CACTUS 10ML",
    quantity: 1,
    price: "2300",
    d_price: "2000",
  },
  {
    id: 12,
    image: "products/w3.jpg",
    quantity: 1,
    title: "CACTUS 10ML",
    price: "1000",
    d_price: "2000",
  },
];
export default wproducts;
